# Statistiques

Vous avez les statistiques salariales suivantes :


In [2]:
import numpy as np
def print_title(title, length = 80):
    print('-' * (length - len(title) - 1), ' ', title, sep='')
    
def print_result(statement_string):
    print_title(statement_string)
    print(eval(statement_string))
    
def print_demo(title, statement_string):
    print_title(title)
    print_result(statement_string)    

salaire_horaire = [ 9.50, 33.50, 30.25, 10.75, 41.50, 16.75, 18.00, 15.50, 21.00,
                   15.25, 21.50, 38.00, 25.25, 42.00, 25.00, 18.75, 37.25, 38.50,
                   40.00, 41.00]
heures_par_semaine = 37.5           # nombre d'heures travaillées par semaine
semaine_par_annee = 52              # nombre de semaines payées par année


data1 = np.array([ 9.50, 33.50, 30.25, 10.75, 41.50, 16.75, 18.00, 15.50, 21.00,
                   15.25, 21.50, 38.00, 25.25, 42.00, 25.00, 18.75, 37.25, 38.50,
                   40.00, 41.00])

## 1) On vous demande de : 
 1. calculer la masse salariale hebdomaraire
 1. calculer la moyenne salariale annuelle
 1. calculer le salaire horaire médian
 1. produire la liste de tous les salaires inférieurs à 15.50 \$/heure
 1. calculer combien d'employé font au moins 30.00 \$/heure
 1. calculer le coût annuel d'une augmentation de la masse salariale de 2.5% uniquement pour les employés faisant moins de 25.00 \$/heure

Les résultats attendus sont :
<pre>
01) Masse salariale hebdomaraire :
    20221.88 $
02) Moyenne salariale annuelle :
    52576.88 $
03) Salaire horaire médian :
    25.12 $
04) Salaires inférieurs à 15.5 $/h :
    9.50 $  -  10.75 $  -  15.25 $
05) Nombre d'employés avec salaire >= 30 $/h :
    9
06) Coût d'une augmentation de 2.5% pour salaires < 25 $/h :
    7166.25 $
</pre>

In [3]:
print_title('question 1')
print_result('np.sum(data1) *heures_par_semaine')
print_title('question 2')
print_result('np.average(salaire_horaire)* heures_par_semaine * semaine_par_annee')
print_title('question 3')
print_result('np.median(data1)')
print_title('question 4')
print_result('data1[data1 < 15.50]')
print_title('question 5')
print_result('np.count_nonzero(data1[data1 >= 30.00])')
print_title('question 6')
moyenne_plus_25 = np.sum(data1[data1 < 25.00] *(heures_par_semaine * semaine_par_annee))
mulit_moyenne = moyenne_plus_25 + (moyenne_plus_25 * (2.5/100))
final = mulit_moyenne - moyenne_plus_25 
print_result('final')


# print(f'réponse {semaine_par_annee}')

--------------------------------------------------------------------- question 1
---------------------------------------------- np.sum(data1) *heures_par_semaine
20221.875
--------------------------------------------------------------------- question 2
------------ np.average(salaire_horaire)* heures_par_semaine * semaine_par_annee
52576.875
--------------------------------------------------------------------- question 3
--------------------------------------------------------------- np.median(data1)
25.125
--------------------------------------------------------------------- question 4
----------------------------------------------------------- data1[data1 < 15.50]
[ 9.5  10.75 15.25]
--------------------------------------------------------------------- question 5
---------------------------------------- np.count_nonzero(data1[data1 >= 30.00])
9
--------------------------------------------------------------------- question 6
------------------------------------------------------------

<hr>

# Géométrie

Une image binaire est une image pour laquelle chaque pixel est soit 0 ou 1.

## 2) On vous demande de créer toutes les fonctions suivantes sans faire de boucle :
1. Faites une fonction qui crée une image binaire de dimension paramétrable dont tous les pixels sont initialisés à 0. À vous de déterminer le meilleur type pour ce type d'image.
<br>`create_image(size)`
<br>&nbsp;&nbsp;&nbsp;- `size` est un tuple indiquant la taille de l'image : `(largeur, hauteur)`.
<br>&nbsp;&nbsp;&nbsp;- `return` l'image produite de type `np.ndarray`.
1. Faites une fonction qui rempli l'image de la même couleur.
<br>`fill(image, color=1)` 
<br>&nbsp;&nbsp;&nbsp;- `image` est l'image à modifier
<br>&nbsp;&nbsp;&nbsp;- `color` la couleur à remplir : `0` ou `1`
<br>&nbsp;&nbsp;&nbsp;- `return` rien, cette fonction modifie l'image passé en argument (`image`) 
1. Faites une fonction qui réinitialise le contenu de l'image (tous les pixels à `0`).
<br>`clear(image)` 
<br>&nbsp;&nbsp;&nbsp;- `image` est l'image à modifier
<br>&nbsp;&nbsp;&nbsp;- `return` rien, cette fonction modifie l'image passé en argument (`image`) 
1. Faites une fonction qui met tous les pixels de l'image à une couleur aléatoire.
<br>`randomize(image, percent=0.5)` 
<br>&nbsp;&nbsp;&nbsp;- `image` est l'image à modifier
<br>&nbsp;&nbsp;&nbsp;- `percent` est le pourcentage de pixel à `1` : `[0., 1.]`
<br>&nbsp;&nbsp;&nbsp;- `return` rien, cette fonction modifie l'image passé en argument (`image`) 
1. Faites une fonction qui trace un seul point dans l'image.
<br>`draw_point(image, point, color=1)` 
<br>&nbsp;&nbsp;&nbsp;- `image` est l'image à modifier
<br>&nbsp;&nbsp;&nbsp;- `point` un tuple de la coordonnée du point à tracer : `(x, y)`
<br>&nbsp;&nbsp;&nbsp;- `color` la couleur à tracer : `0` ou `1`
<br>&nbsp;&nbsp;&nbsp;- `return` rien, cette fonction modifie l'image passé en argument (`image`) 
<br>_si le point se trouve à l'extérieur de l'image, la fonction est sans effet_
1. Faites une fonction qui trace un rectangle rempli dans l'image. 
<br>`draw_rectangle(image, top_left, bottom_right)` 
<br>&nbsp;&nbsp;&nbsp;- `image` est l'image à modifier
<br>&nbsp;&nbsp;&nbsp;- `top_left` un tuple de la coordonnée supérieure gauche : `(x0, y0)`
<br>&nbsp;&nbsp;&nbsp;- `bottom_right` un tuple de la coordonnée inférieure droite  : `(x1, y1)`
<br>&nbsp;&nbsp;&nbsp;- **attention** `bottom_right` est une frontière exclue
<br>&nbsp;&nbsp;&nbsp;- `return` rien, cette fonction modifie l'image passé en argument (`image`) 
<br>_si le rectangle dépasse l'image tout ou en partie, seulement la partie visible est tracée_
1. Faites une fonction qui met tous les pixels de la bordure à 0.
<br>`reset_border(image)` 
<br>&nbsp;&nbsp;&nbsp;- `image` est l'image à modifier
<br>&nbsp;&nbsp;&nbsp;- `return` rien, cette fonction modifie l'image passé en argument (`image`) 
1. Faites une fonction qui trace un point de la couleur spécifiée à une position aléatoire. La position est n'importe où à l'intérieur de l'image.
<br>`draw_random_point(image, color=1)` 
<br>&nbsp;&nbsp;&nbsp;- `image` est l'image à modifier
<br>&nbsp;&nbsp;&nbsp;- `color` la couleur à tracer : `0` ou `1`
<br>&nbsp;&nbsp;&nbsp;- `return` rien, cette fonction modifie l'image passé en argument (`image`) 
<br>_cette fonction peut dessiner la même couleur sur un pixel, ce qui n'aura aucun effet visible_
1. Faites une fonction qui inverse un point de l'image à une position aléatoire. La position doit être aléatoire parmi les pixels de la couleur donnée.
<br>`inverse_random_point(image, color=0)` 
<br>&nbsp;&nbsp;&nbsp;- `image` est l'image à modifier
<br>&nbsp;&nbsp;&nbsp;- `color` est la couleur à considérer pour l'analyse des positions disponibles : `0` ou `1`
<br>&nbsp;&nbsp;&nbsp;- `return` rien, cette fonction modifie l'image passé en argument (`image`) 
<br>_s'il n'existe aucun pixel de la couleur spécifiée, la fonction est sans effet_
1. Faites une fonction calculant la distance entre 2 points de l'image.
<br>`distance_between_two_points(image)` 
<br>&nbsp;&nbsp;&nbsp;- `image` est l'image à analyser
<br>&nbsp;&nbsp;&nbsp;- `return` un `float` représentant la distance calculée, retourne `None` si l'image ne possède pas strictement deux points
<br>_cette fonction considère que toute l'image est à 0 et que seulement 2 points sont à 1 - ainsi, c'est la distance entre ces deux points qui doit être retournée_
1. Faites une fonction qui trace un cercle rempli dans l'image.
<br>`draw_circle(image, center, radius)` 
<br>&nbsp;&nbsp;&nbsp;- `image` est l'image à modifier
<br>&nbsp;&nbsp;&nbsp;- `center` est une tuple représentant la coordonnée du centre : `(cx, cy)`
<br>&nbsp;&nbsp;&nbsp;- `radius` est le rayon du cercle
<br>&nbsp;&nbsp;&nbsp;- `return` rien, cette fonction modifie l'image passé en argument (`image`) 
<br>_si le cercle dépasse l'image tout ou en partie, seulement la partie visible est tracée_
1. Considérant qu'une seule forme se trouve dans l'image, faites une fonction qui calcule l'aire de la forme.
<br>`area(image)` 
<br>&nbsp;&nbsp;&nbsp;- `image` est l'image à considérer
<br>&nbsp;&nbsp;&nbsp;- `return` un `float` représentant l'aire calculée
<br>$$ area = \sum_{} I_{x,y}, \forall x,y\in shape $$
<br>où :
<br>&nbsp;&nbsp;&nbsp;- $I_{x,y}$ est la valeur de l'image à la coordonnées $x$ et $y$
<br>&nbsp;&nbsp;&nbsp;- $x$ est la coordonnées sur les abscisses
<br>&nbsp;&nbsp;&nbsp;- $y$ est la coordonnées sur les ordonnées
1. Considérant qu'une seule forme se trouve dans l'image, faites une fonction qui calcule le centroïde de la forme.
<br>`centroid(image)` 
<br>&nbsp;&nbsp;&nbsp;- `image` est l'image à considérer
<br>&nbsp;&nbsp;&nbsp;- `return` un `tuple` de deux `float` représentant la coordonnée du centroïde.
<br>_le centroïde est ce qu'on appel en physique le centre de masse et correspond au point d'équilibre de tous les pixels à 1_
<br>$$ centroid = \left(C_x, C_y\right) = \frac{\left(\sum x I_{x,y}, \sum y I_{x,y}\right)}{area}, \forall x,y\in shape $$
<br>où :
<br>&nbsp;&nbsp;&nbsp;- $I_{x,y}$ est la valeur de l'image à la coordonnées $x$ et $y$
<br>&nbsp;&nbsp;&nbsp;- $x$ est la coordonnées sur les abscisses
<br>&nbsp;&nbsp;&nbsp;- $y$ est la coordonnées sur les ordonnées
1. Considérant qu'une seule forme se trouve dans l'image et que les bordures sont à 0, faites une fonction qui calcule le périmètre de la forme.
<br>`perimeter(image)`
<br>&nbsp;&nbsp;&nbsp;- `image` est l'image à considérer
<br>&nbsp;&nbsp;&nbsp;- `return` un `float` représentant le périmètre de la forme.
<br>__attention__ _cet exercice présente un niveau de difficulté __beaucoup__ plus élevé_ __<---__


In [47]:
print_title('question 1')
def create_binary_image(width, height):
    """
    Crée une image binaire de dimension paramétrable.

    Args:
    - width (int): Largeur de l'image.
    - height (int): Hauteur de l'image.

    Returns:
    - numpy.ndarray: Image binaire avec tous les pixels initialisés à 0.
    """
    # Créer une matrice de forme (height, width) remplie de zéros
    binary_image = np.zeros((height, width), dtype=np.uint8)
    return binary_image
        
image = create_binary_image(100, 50)
print_result('image')    

print_title('question 2')
def fill(image, color=1):
    """
    Remplit l'image de la même couleur.

    Args:
    - image (numpy.ndarray): L'image à modifier.
    - color (int): La couleur à remplir (0 ou 1).

    Returns:
    - None: Cette fonction modifie l'image passée en argument.
    """
    # Utilisez la fonction np.ones_like pour créer une matrice de la même forme que l'image,
    # remplie de la valeur spécifiée par 'color'.
    image[:] = np.ones_like(image) * color

image = create_binary_image(100, 50)
fill(image, color=1)
print_result('image')   

print_title('question 3')
def clear(image):
    """
    Réinitialise le contenu de l'image en mettant tous les pixels à 0.

    Args:
    - image (numpy.ndarray): L'image à réinitialiser.

    Returns:
    - None: Cette fonction modifie l'image passée en argument.
    """
    # Utilisez la fonction np.zeros_like pour remplir l'image de zéros.
    image[:] = np.zeros_like(image)

image = create_binary_image(100, 50)
fill(image, color=1)
print("Image avant la réinitialisation:")
print_result('image')

# Réinitialisation de l'image
clear(image)

print("\nImage après la réinitialisation:")
print_result('image')

print_title('question 4')
def randomize(image, percent=0.5):
    """
    Met tous les pixels de l'image à une couleur aléatoire en respectant un pourcentage donné.

    Args:
    - image (numpy.ndarray): L'image à modifier.
    - percent ( tjrs float?): Le pourcentage de pixels à 1, doit être compris entre 0 et 1.

    Returns:
    - None: Cette fonction modifie l'image passée en argument.
    """
    # Génère une matrice aléatoire de la même forme que l'image avec des valeurs entre 0 et 1.
    random_matrix = np.random.rand(*image.shape)

    # Les pixels seront mis à 1 si la valeur aléatoire est inférieure ou égale au pourcentage spécifié.
    image[random_matrix <= percent] = 1
    # Les pixels seront mis à 0 sinon.
    image[random_matrix > percent] = 0

image = create_binary_image(10, 5)
randomize(image, percent=0.3)
print_result('image')

# print_title('question 5')
def draw_point(image, point, color=1):
    """
    Trace un seul point dans l'image.

    Args:
    - image (numpy.ndarray): L'image à modifier.
    - point : Coordonnées du point à tracer (x, y).
    - color (int): La couleur à tracer (0 ou 1).

    Returns:
    - None: Cette fonction modifie l'image passée en argument.
    """
    # Récupère les coordonnées du point.
    x, y = point
    
    # Vérifie si le point est à l'intérieur des dimensions de l'image.
    if 0 <= x < image.shape[1] and 0 <= y < image.shape[0]:
        # Modifie la valeur du pixel à la position spécifiée.
        image[y, x] = color

image = create_binary_image(5, 5)
draw_point(image, (2, 2), color=1)
print_result('image')


print_title('question 6')
def draw_rectangle(image,top_left,bottom_right):
    """"
    Trace un rectangle rempli dans l'image. 
    Args:
    - image (numpy.ndarray): L'image à modifier.
    - top_left (tuple) : coordonnée supérieure gauche (x,y)
    - bottom_right : un tuple de la coordonnée inférieure droite, est une frontière exclue (x,y)
    
    returns:
    - None: Cette fonction modifie l'image passée en argument.
    """    
    ## Récupère les coordonnées du top left.
    x0, y0 = top_left
    ## Récupère les coordonnées du top left.
    x1, y1 = bottom_right
    
     # Vérifie si le point est à l'intérieur des dimensions de l'image.
    if 0 <= x0 < image.shape[1] and 0 <= y0 < image.shape[0]:
        # Modifie la valeur du pixel à la position spécifiée.
       image[y0:y1, x0:x1] = 1
        
image = create_binary_image(10, 10)
draw_rectangle(image, (1, 1),(3, 3))
print_result('image')

print_title('question 7')
def reset_border(image):
    """"
    Met tous les pixels de la bordure à 0
    Args:
    - image (numpy.ndarray): L'image à modifier.
    
    
    returns:
    - None: Cette fonction modifie l'image passée en argument.
    """    
    image[1:3] = np.ones_like(image) * 1
      

image = create_binary_image(5, 5)
fill(image)  
image[:,0] = 0
image[:,-1] = 0
image[0,:] = 0
image[-1:,:] = 0
print_result('image')


print_title('question 8')
def draw_random_point(image, color):
    """"
   
    Faites une fonction qui trace un point de la couleur spécifiée à une position aléatoire. La position est n'importe où à l'intérieur de l'image.
    Args:
    - image (numpy.ndarray): L'image à modifier.
    - color` la couleur à tracer : `0` ou `1`

    returns:
    - None: Cette fonction modifie l'image passée en argument.
    """    
      # Récupère les coordonnées du point.
    x, y = np.random.randint(0, image.shape[1]), np.random.randint(0, image.shape[0])
    
    # Vérifie si le point est à l'intérieur des dimensions de l'image.
    if 0 <= x < image.shape[1] and 0 <= y < image.shape[0]:
        # Modifie la valeur du pixel à la position spécifiée.
        image[y, x] = color

image = create_binary_image(5, 5)
draw_random_point(image, color=1)
print_result('image')

print_title('question 9')
def draw_random_point(image, color):
    """"
    Inverse un point de l'image à une position aléatoire parmi les pixels de la couleur spécifiée.

    Args:
    - image (numpy.ndarray): L'image à modifier.
    - color (int): La couleur à considérer pour l'analyse des positions disponibles (0 ou 1).

    Returns:
    - None: Cette fonction modifie l'image passée en argument.
    """    
      # Récupère les coordonnées du point.
    x, y = np.random.randint(0, image.shape[1]), np.random.randint(0, image.shape[0])
    
    # Vérifie si le point est à l'intérieur des dimensions de l'image.
    if 0 <= x < image.shape[1] and 0 <= y < image.shape[0]:
        # Modifie la valeur du pixel à la position spécifiée.
        image[y, x] = color

image = create_binary_image(5, 5)
draw_random_point(image, color=1)
print_result('image')

print_title('question 9')
def inverse_random_point(image, color=0):
    """
    Inverse un point de l'image à une position aléatoire parmi les pixels de la couleur spécifiée.

    Args:
    - image (numpy.ndarray): L'image à modifier.
    - color (int): La couleur à considérer pour l'analyse des positions disponibles (0 ou 1).

    Returns:
    - None: Cette fonction modifie l'image passée en argument.
    """
    # Trouver les indices des pixels de la couleur spécifiée
    indices = np.where(image == color)

    # Vérifier s'il y a des pixels de la couleur spécifiée
    if len(indices[0]) > 0:
        # Choisir un indice aléatoire parmi les pixels de la couleur spécifiée
        random_index = np.random.choice(len(indices[0]))

        # Récupérer les coordonnées du pixel à inverser
        y, x = indices[0][random_index], indices[1][random_index]

        # Inverser la couleur du pixel à la position spécifiée
        image[y, x] = 1 - color
print_title('question 10')
def distance_between_two_points(image):
    """
    Calcule la distance entre deux points dans l'image.

    Args:
    - image (numpy.ndarray): L'image à analyser.

    Returns:
    - float: La distance entre les deux points.
    - None: Si l'image ne possède pas strictement deux points.
    """
    # Trouver les indices des pixels à 1 dans l'image
    indices = np.argwhere(image == 1)

    # Vérifier s'il y a exactement deux points dans l'image
    if len(indices) == 2:
        # Calculer la distance entre les deux points
        point1, point2 = indices
        distance = np.linalg.norm(point1 - point2)
        return distance
    else:
        # S'il n'y a pas exactement deux points, retourner None
        return None

# Exemple d'utilisation
image_with_two_points = np.array([[0, 0, 0, 0, 0],
                                  [0, 0, 1, 0, 0],
                                  [0, 0, 0, 0, 0]])

image_with_three_points = np.array([[0, 0, 0, 0, 0],
                                    [0, 1, 0, 1, 0],
                                    [0, 0, 0, 0, 0]])

distance1 = distance_between_two_points(image_with_two_points)
distance2 = distance_between_two_points(image_with_three_points)

print("Distance entre deux points dans l'image 1:", distance1)
print("Distance entre deux points dans l'image 2:", distance2)

print_title('question 11')
def draw_circle(image, center, radius):
    """
    Trace un cercle rempli dans l'image.

    Args:
    - image (numpy.ndarray): L'image à modifier.
    - center (tuple): Coordonnées du centre du cercle (cx, cy).
    - radius (int): Rayon du cercle.

    Returns:
    - None: Cette fonction modifie l'image passée en argument.
    """
    # Récupère les coordonnées de la grille
    c, r = np.meshgrid(np.arange(image.shape[1]), np.arange(image.shape[0]))

    # Calcule la distance euclidienne de chaque pixel par rapport au centre du cercle
    dist = np.sqrt((r - center[1])**2 + (c - center[0])**2)

    # Crée un masque pour le cercle
    circle = (dist <= radius).astype(np.uint8)

    # Combine le cercle tracé avec l'image existante en utilisant l'opérateur logique "or"
    image[:,:] = np.logical_or(image[:,:], circle)


    # Example usage
image_size = 10
image = np.zeros((image_size, image_size), dtype=np.uint8)
draw_circle(image, center=(5, 5), radius=3)

# Print the resulting image
print(image)

print_title('question 12')
def area(image):
    """
    Calcule l'aire de la forme dans l'image.

    Args:
    - image (numpy.ndarray): L'image à considérer.

    Returns:
    - float: L'aire calculée.
    """
    return np.sum(image)

# Exemple d'utilisation
image_size = 5
image = np.array([[0, 0, 0, 0, 0],
                  [0, 1, 1, 1, 0],
                  [0, 1, 1, 1, 1],
                  [0, 1, 1, 1, 0],
                  [0, 0, 0,0 , 0]])

# Calcule l'aire de la forme dans l'image
shape_area = area(image)

# Affiche l'image et l'aire calculée
print("Image:")
print(image)
print("Aire de la forme dans l'image:", shape_area)

print_title('question 13')
def centroid(image):
    """
    Calcule le centroïde de la forme dans l'image.

    Args:
    - image (numpy.ndarray): L'image à considérer.

    Returns:
    - tuple: Coordonnées du centroïde (Cx, Cy).
    """
    # Crée des tableaux de coordonnées pour chaque pixel de l'image
    c, r = np.meshgrid(np.arange(image.shape[1]), np.arange(image.shape[0]))

    # Calcule les coordonnées pondérées du centroïde
    centroid_x = np.sum(c * image) / np.sum(image)
    centroid_y = np.sum(r * image) / np.sum(image)

    return (centroid_x, centroid_y)

# Exemple d'utilisation
image_size = 5
image = np.array([[0, 0, 0, 0, 0],
                  [0, 1, 1, 1, 0],
                  [0, 1, 1, 1, 1],
                  [0, 1, 1, 1, 0],
                  [0, 0, 0,0 , 0]])

# Calcule le centroïde de la forme dans l'image
shape_centroid = centroid(image)

# Affiche l'image et le centroïde calculé
print("Image:")
print(image)
print("Centroïde de la forme dans l'image:", shape_centroid)

print_title('question 14')
def perimeter(image):
    """
    Calcule le périmètre de la forme dans l'image.

    Args:
    - image (numpy.ndarray): L'image à considérer.

    Returns:
    - float: Périmètre de la forme.
    """
    # Vérifie si l'image est vide
    if np.sum(image) == 0:
        return 0.0

    # Crée une copie de l'image pour éviter de modifier l'originale
    bordered_image = np.pad(image, pad_width=1, mode='constant', constant_values=0)

    # Trouve les indices des pixels de bordure qui ont au moins un voisin différent
    border_pixels = np.argwhere((bordered_image[1:-1, 1:-1] == 1) & (
        (bordered_image[:-2, 1:-1] == 0) | (bordered_image[2:, 1:-1] == 0) |
        (bordered_image[1:-1, :-2] == 0) | (bordered_image[1:-1, 2:] == 0)
    ))

    # Calcule le périmètre en utilisant la longueur du contour
    perimeter_value = len(border_pixels)

    return perimeter_value

# Exemple d'utilisation
image_size = 5
image = np.array([[0, 0, 0, 0, 0],
                  [0, 1, 1, 1, 0],
                  [0, 1, 1, 1, 1],
                  [0, 1, 1, 1, 0],
                  [0, 0, 0,0 , 0]])

# Calcule le périmètre de la forme dans l'image
shape_perimeter = perimeter(image)

# Affiche l'image et le périmètre calculé
print("Image:")
print(image)
print("Périmètre de la forme dans l'image:", shape_perimeter)

def perimetre(image):
    """
    Calcule le périmètre de la forme dans l'image.

    Args:
    - image (numpy.ndarray): L'image à considérer.

    Returns:
    - float: Périmètre de la forme.
    """
    lignes, colonnes = image.shape
    perimetre_valeur = 0

    for i in range(lignes):
        for j in range(colonnes):
            if image[i, j] == 1:
                perimetre_valeur += 4  # Chaque pixel contribue à 4 au périmètre

                # Soustraire 2 pour chaque bord interne (voisins de gauche et du haut)
                if i > 0 and image[i - 1, j] == 1:
                    perimetre_valeur -= 2
                if j > 0 and image[i, j - 1] == 1:
                    perimetre_valeur -= 2

    return perimetre_valeur

# Exemple d'utilisation
taille_image = 5
image = np.array([[0, 0, 0, 0, 0],
                  [0, 1, 1, 1, 0],
                  [0, 1, 1, 1, 1],
                  [0, 1, 1, 1, 0],
                  [0, 0, 0,0 , 0]])

# Calculer le périmètre de la forme dans l'image
perimetre_forme = perimetre(image)

# Afficher l'image et le périmètre calculé
print("Image :")
print(image)
print("Périmètre de la forme dans l'image :", perimetre_forme)

--------------------------------------------------------------------- question 1
-------------------------------------------------------------------------- image
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
--------------------------------------------------------------------- question 2
-------------------------------------------------------------------------- image
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
--------------------------------------------------------------------- question 3
Image avant la réinitialisation:
-------------------------------------------------------------------------- image
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]

Image après la réinitialisation:
-------------------------------------------------------------------------- image
[[0 0 